config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :practices, only: [:index, :show, :edit, :update]
  post "practices/:id/select", to: "practices#select", as: :select_practice

  # OAuth routes
  get "/oauth/:provider/callback", to: "identities#create"
  post "/oauth/:provider/callback", to: "identities#create"
  get "/oauth/failure", to: "identities#failure"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :passwords, param: :token

  namespace :graphical do
    resources :dental_models, only: [:show]
  end

  namespace :admin do
    resources :users
    resource :dashboard, only: [:show]
    resources :organizations do
      resources :practices
    end
    resources :practices
    resources :identity_providers
  end

  get "home", to: "home#show"
  root "home#show"

  get "up" => "rails/health#show", :as => :rails_health_check
end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
# Database name: primary
#
#  id                  :uuid             not null, primary key
#  chart_number        :string           not null
#  dental_models_count :integer          default(0), not null
#  patient_number      :string           not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  practice_id         :uuid             not null
#
# Indexes
#
#  index_patients_on_practice_id                     (practice_id)
#  index_patients_on_practice_id_and_patient_number  (practice_id,patient_number) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (practice_id => practices.id)
#
class Patient < ApplicationRecord
  include ShortReadableRandomID

  belongs_to :practice, counter_cache: true
  has_many :dental_models, dependent: :destroy

  validates :chart_number, presence: true
  validates :patient_number, presence: true, uniqueness: {scope: :practice_id}

  before_validation(on: :create) { set_patient_number }

  def set_patient_number
    self.patient_number = generate_unique_hrid(:patient_number, practice_id: practice_id)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[show edit update destroy]

  authorize_resource

  # GET /patients or /patients.json
  def index
    @patients = Current.practice.patients.includes([:dental_models]).all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_content }
        format.json { render json: @patient.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: "Patient was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_content }
        format.json { render json: @patient.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy!

    respond_to do |format|
      format.html { redirect_to patients_path, notice: "Patient was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Current.practice.patients.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def patient_params
    params.fetch(:patient, {})
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, class: "contents") do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul class="list-disc ml-6">
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>" class="w-full sm:w-auto my-5 space-y-5">

  <p><strong><%= patient.patient_number %>
      -
      <%= patient.chart_number %></strong></p>

  <p><strong>Models:</strong>
    <%= patient.dental_models.count %></p>
  <ul>
    <% patient.dental_models.each do |dental_model| %>
      <li><%= link_to dental_model.name, graphical_dental_model_path(dental_model) %></li>
    <% end %>
  </ul>

</div>

app/views/patients/edit.html.erb
<% content_for :title, "Editing patient" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing patient</h1>

  <%= render "form", patient: @patient %>

  <%= link_to "Show this patient", @patient, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to patients", patients_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/patients/index.html.erb
<% content_for :title, "Patients" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Patients</h1>
    <%= link_to "New patient", new_patient_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="patients" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @patients.any? %>
      <% @patients.each do |patient| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render patient %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", patient, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_patient_path(patient), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", patient, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No patients found.</p>
    <% end %>
  </div>
</div>

app/views/patients/new.html.erb
<% content_for :title, "New patient" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New patient</h1>

  <%= render "form", patient: @patient %>

  <%= link_to "Back to patients", patients_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/patients/show.html.erb
<% content_for :title, "Showing patient" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing patient</h1>

  <%= render @patient %>

  <%= link_to "Edit this patient", edit_patient_path(@patient), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to patients", patients_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this patient", @patient, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>